# Site settings
# in the templates available like {{ site.myvariable }}.
title: Gwendaël Frin - Coiffeur/Maquilleur - Paris
email: gwendael.frin@gmail.com
brand: Gwendaël Frin
headline: Coiffeur / Maquilleur
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2018 Gwendaël Frin. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 527312

# Contacts
email: gwendael.frin@gmail.com
phone: 0607279653

# Tracking
googleAnalitycsID: UA-83933844-1

